### ISSUE TITLE
Fix tests.

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/secure-data-hub-client#1]
The `tests` branch (https://github.com/digitalbazaar/data-hub-client/tree/tests) is supposed to:

- bring over the tests from https://github.com/digitalbazaar/bedrock-web-data-hub/
- get tests running in both browser (with karma testing) and in node
- the intent is that this module can be a browser and node replacement for `bedrock-web-data-hub`

 I did have the `bedrock-web-data-hub` tests running using this module (see https://github.com/digitalbazaar/bedrock-web-data-hub/tree/data-hub-client) but apparently that somehow broke.
[EDIT: bedrock-karma 1.4 broke things, tests will run with 1.3]

Tasks:
- [x] Fix tests to run again in karma.
- [x] Remove bedrock things from the tests.  Some of the 'bedrock-web' test deps may actually work in node.  It may makes sense to just merge them in here?  Need to look into this.
- [x] Get tests to run in node.  There are a few WebCrypto calls that need to be fixed up for this.  The likely approach is to move browser specifics into a file (foo-browser.js), add a file with a node implementation (foo.js), and use the package.json browser override to map the node file to the browser one for bundler use.

**Comment by aljones15** [comment]
@davidlehn just to keep you updated Pretender employs an IIFE pattern which means that on import or require it causes the node tests to fail. I am currently trying to stub it out, but that can be difficult as mocha spawns a different node process for each test. proxyquire can be used to handle this, but would need to be conditional. I'm also pretty close to mock keypair data too.
